Repository UdL-EPS-SoftArch/seedbank-gei-api, pull requests merged in 2023-03, with the labels that each got.

#18 feat: admin entity
  src/main/java/cat/udl/eps/softarch/demo/domain/Admin.java
Labels: feature

#24 Test feat delete donation
  src/test/java/cat/udl/eps/softarch/demo/steps/DonationStepDefs.java
  src/test/resources/features/DeleteDonation.feature
Labels: feature

#21 Feat task Solving id test errors
  src/main/java/cat/udl/eps/softarch/demo/domain/Take.java
  src/main/java/cat/udl/eps/softarch/demo/repository/TakeRepository.java
  src/test/java/cat/udl/eps/softarch/demo/steps/CreateTakeStepDefs.java
  src/test/java/cat/udl/eps/softarch/demo/steps/DeleteTakeStepDefs.java
  src/test/java/cat/udl/eps/softarch/demo/steps/GetTakeStepDefs.java
  src/test/java/cat/udl/eps/softarch/demo/steps/UpdateTakeStepDefs.java
  src/test/resources/features/CreateTake.feature
  src/test/resources/features/DeleteTake.feature
  src/test/resources/features/GetTake.feature
  src/test/resources/features/UpdateTake.feature
Labels: feature

#29 Refactor seed
  src/main/java/cat/udl/eps/softarch/demo/domain/Seed.java
Labels: enhancement

#33 Test retrieve donation
  src/test/java/cat/udl/eps/softarch/demo/steps/DonationStepDefs.java
  src/test/resources/features/RetrieveDonation.feature
Labels: enhancement

#35 test: update donation
  src/test/java/cat/udl/eps/softarch/demo/steps/DonationStepDefs.java
  src/test/resources/features/UpdateDonation.feature
Labels: enhancement

#36 test: update donation
  src/main/java/cat/udl/eps/softarch/demo/domain/UriEntity.java
  src/test/java/cat/udl/eps/softarch/demo/steps/DonationStepDefs.java
  src/test/resources/features/UpdateDonation.feature
Labels: enhancement

#39 Propagator background for take in step defs.
  src/main/java/cat/udl/eps/softarch/demo/domain/Batch.java
  src/main/java/cat/udl/eps/softarch/demo/domain/Propagator.java
  src/main/java/cat/udl/eps/softarch/demo/domain/Take.java
  src/test/java/cat/udl/eps/softarch/demo/mothers/PropagatorMother.java
  src/test/java/cat/udl/eps/softarch/demo/steps/CreateTakeStepDefs.java
  src/test/java/cat/udl/eps/softarch/demo/steps/DeleteTakeStepDefs.java
  src/test/java/cat/udl/eps/softarch/demo/steps/RegisterStepDefs.java
  src/test/resources/features/DeleteTake.feature
Labels: enhancement, feature

#41 test: retrieve request
  src/test/java/cat/udl/eps/softarch/demo/steps/RequestStepDefs.java
  src/test/resources/features/RetrieveRequest.feature
Labels: enhancement

#43 test: update request
  src/main/java/cat/udl/eps/softarch/demo/domain/UriEntity.java
  src/test/java/cat/udl/eps/softarch/demo/steps/RequestStepDefs.java
  src/test/resources/features/UpdateRequest.feature
Labels: enhancement

#45 test: delete request
  src/test/java/cat/udl/eps/softarch/demo/steps/RequestStepDefs.java
  src/test/resources/features/DeleteRequest.feature
Labels: enhancement
